// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type ParamMatchFragment<Route extends keyof ParamMap> = Partial<Record<keyof ParamMap[Route], string>>
type ParamMatchingExports<Route extends keyof ParamMap> =
  | { unstable_paramMatching?: ParamMatchFragment<Route>; unstable_generateParamMatching?: never }
  | { unstable_paramMatching?: never; unstable_generateParamMatching?: () => Promise<ParamMatchFragment<Route>> | ParamMatchFragment<Route> }

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
} & ParamMatchingExports<Route>

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
} & ParamMatchingExports<Route>


// Validate ../../../app/cv/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cv">> = Specific
  const handler = {} as typeof import("../../../app/cv/page.js")
  type __Check = __IsExpected<typeof handler>
  
  type __ParamMatchingValue =
    typeof handler extends { unstable_paramMatching: infer Matcher } ? Matcher :
    typeof handler extends { unstable_generateParamMatching: (...args: any[]) => infer Matcher } ? Awaited<Matcher> : {}
  type __InvalidParamMatchingKeys = Exclude<keyof __ParamMatchingValue, keyof ParamMap["/cv"]>
  type __AssertNoInvalidParamMatchingKeys<Invalid extends never> = Invalid
  const __paramMatchingKeyCheck: __AssertNoInvalidParamMatchingKeys<__InvalidParamMatchingKeys> | undefined = undefined
  void __paramMatchingKeyCheck
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  
  type __ParamMatchingValue =
    typeof handler extends { unstable_paramMatching: infer Matcher } ? Matcher :
    typeof handler extends { unstable_generateParamMatching: (...args: any[]) => infer Matcher } ? Awaited<Matcher> : {}
  type __InvalidParamMatchingKeys = Exclude<keyof __ParamMatchingValue, keyof ParamMap["/"]>
  type __AssertNoInvalidParamMatchingKeys<Invalid extends never> = Invalid
  const __paramMatchingKeyCheck: __AssertNoInvalidParamMatchingKeys<__InvalidParamMatchingKeys> | undefined = undefined
  void __paramMatchingKeyCheck
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/projects/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/projects/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  
  type __ParamMatchingValue =
    typeof handler extends { unstable_paramMatching: infer Matcher } ? Matcher :
    typeof handler extends { unstable_generateParamMatching: (...args: any[]) => infer Matcher } ? Awaited<Matcher> : {}
  type __InvalidParamMatchingKeys = Exclude<keyof __ParamMatchingValue, keyof ParamMap["/projects/[slug]"]>
  type __AssertNoInvalidParamMatchingKeys<Invalid extends never> = Invalid
  const __paramMatchingKeyCheck: __AssertNoInvalidParamMatchingKeys<__InvalidParamMatchingKeys> | undefined = undefined
  void __paramMatchingKeyCheck
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects">> = Specific
  const handler = {} as typeof import("../../../app/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  
  type __ParamMatchingValue =
    typeof handler extends { unstable_paramMatching: infer Matcher } ? Matcher :
    typeof handler extends { unstable_generateParamMatching: (...args: any[]) => infer Matcher } ? Awaited<Matcher> : {}
  type __InvalidParamMatchingKeys = Exclude<keyof __ParamMatchingValue, keyof ParamMap["/projects"]>
  type __AssertNoInvalidParamMatchingKeys<Invalid extends never> = Invalid
  const __paramMatchingKeyCheck: __AssertNoInvalidParamMatchingKeys<__InvalidParamMatchingKeys> | undefined = undefined
  void __paramMatchingKeyCheck
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  
  type __ParamMatchingValue =
    typeof handler extends { unstable_paramMatching: infer Matcher } ? Matcher :
    typeof handler extends { unstable_generateParamMatching: (...args: any[]) => infer Matcher } ? Awaited<Matcher> : {}
  type __InvalidParamMatchingKeys = Exclude<keyof __ParamMatchingValue, keyof ParamMap["/"]>
  type __AssertNoInvalidParamMatchingKeys<Invalid extends never> = Invalid
  const __paramMatchingKeyCheck: __AssertNoInvalidParamMatchingKeys<__InvalidParamMatchingKeys> | undefined = undefined
  void __paramMatchingKeyCheck
  // @ts-ignore
  type __Unused = __Check
}
